# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bootstrapper}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jared Mehle"]
  s.date = %q{2010-09-30}
  s.email = %q{jrmehle@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "lib/bootstrapper.rb",
     "lib/bootstrapper/bootstrapper.rb",
     "lib/bootstrapper/railtie.rb",
     "lib/connection_adapters/abstract_adapter.rb",
     "lib/connection_adapters/mysql_adapter.rb",
     "lib/generators/bootstrapper_generator.rb",
     "lib/generators/templates/bootstrap.erb",
     "lib/tasks/bootstrap.rake"
  ]
  s.homepage = %q{http://github.com/jrmehle/bootstrapper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{The better way to load seed data (than seeds.rb)}
  s.test_files = [
    "test/bootstrapper_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.0"])
    else
      s.add_dependency(%q<activerecord>, [">= 2.3.0"])
      s.add_dependency(%q<activesupport>, [">= 2.3.0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 2.3.0"])
    s.add_dependency(%q<activesupport>, [">= 2.3.0"])
  end
end

